FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    curl \
    wget \
    build-essential

RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g typescript

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN tsc -b

EXPOSE 8080

CMD ["node", "dist/index.js"]
