export const extensionMap = {
  py: "python",
  js: "javascript",
  ts: "typescript",
  java: "java",
  cpp: "cpp",
  c: "c",
  cs: "c#",
  rb: "ruby", 
  php: "php",
  html: "html5",
  css: "css3",
  json: "json",
  xml: "xml",
  md: "markdown",
  go: "go", // Golang
  rs: "rust",
  kt: "kotlin",
  swift: "swift",
  sh: "shell",
  pl: "perl",
  r: "r",
  m: "matlab",
  hs: "haskell",
  erl: "erlang",
  ex: "elixir",
  vb: "visual basic",
  scala: "scala",
  dart: "dart",
  lua: "lua",
  bat: "batch",
  coffee: "coffeescript",
  clj: "clojure",
  f90: "fortran",
  v: "verilog",
  vhdl: "vhdl",
  asm: "assembly",
  sql: "sql",
  tsx: "typescript jsx",
  jsx: "javascript jsx",
  h: "c header",
  ino: "arduino",
  ps1: "powershell",
  ml: "ocaml",
  elm: "elm",
  rkt: "racket",
  nim: "nim",
  d: "d",
  pas: "pascal",
  ada: "ada",
  jl: "julia",
  fs: "f#",
  hx: "haxe",
  git: "git",
  docker: "docker",
  gitignore: "git",
  next: "nextjs",
  mjs: "javascript",
};
